In [ ]:
import pandas as pd
import numpy as np

t = pd.read_csv('/modules/cs342/Assignment2/training_set.csv',header=0)

In [ ]:
t

In [1]:
import pandas as pd
import numpy as np

t = pd.read_csv('/modules/cs342/Assignment2/sample_submission.csv',header=0)
count=0
for index,row in t.iterrows():
    if count == 10 :
        break
    count += 1
    for column in row:
        column = 15

In [2]:
print t

         object_id  class_6  class_15  class_16  class_42  class_52  class_53  \
0               13        0         0         0         0         0         0
1               14        0         0         0         0         0         0
2               17        0         0         0         0         0         0
3               23        0         0         0         0         0         0
4               34        0         0         0         0         0         0
5               35        0         0         0         0         0         0
6               43        0         0         0         0         0         0
7               50        0         0         0         0         0         0
8               60        0         0         0         0         0         0
9               69        0         0         0         0         0         0
10              88        0         0         0         0         0         0
11              96        0         0         0         0         0         0
12             106        0         0         0         0         0         0
13             114        0         0         0         0         0         0
14             115        0         0         0         0         0         0
15             116        0         0         0         0         0         0
16             130        0         0         0         0         0         0
17             142        0         0         0         0         0         0
18             147        0         0         0         0         0         0
19             151        0         0         0         0         0         0
20             168        0         0         0         0         0         0
21             171        0         0         0         0         0         0
22             173        0         0         0         0         0         0
23             176        0         0         0         0         0         0
24             184        0         0         0         0         0         0
25             186        0         0         0         0         0         0
26             195        0         0         0         0         0         0
27             198        0         0         0         0         0         0
28             204        0         0         0         0         0         0
29             211        0         0         0         0         0         0
...            ...      ...       ...       ...       ...       ...       ...
3492860  130787078        0         0         0         0         0         0
3492861  130787121        0         0         0         0         0         0
3492862  130787259        0         0         0         0         0         0
3492863  130787288        0         0         0         0         0         0
3492864  130787315        0         0         0         0         0         0
3492865  130787346        0         0         0         0         0         0
3492866  130787409        0         0         0         0         0         0
3492867  130787413        0         0         0         0         0         0
3492868  130787553        0         0         0         0         0         0
3492869  130787572        0         0         0         0         0         0
3492870  130787650        0         0         0         0         0         0
3492871  130787683        0         0         0         0         0         0
3492872  130787746        0         0         0         0         0         0
3492873  130787754        0         0         0         0         0         0
3492874  130787792        0         0         0         0         0         0
3492875  130787808        0         0         0         0         0         0
3492876  130787817        0         0         0         0         0         0
3492877  130787819        0         0         0         0         0         0
3492878  130787871        0         0         0         0         0         0
3492879  130787879        0         0         0         0         0         0
3492880  130787887        0         0         0         0         0         0
3492881  130787903        0         0         0         0         0         0
3492882  130787932        0         0         0         0         0         0
3492883  130787944        0         0         0         0         0         0
3492884  130787965        0         0         0         0         0         0
3492885  130787966        0         0         0         0         0         0
3492886  130787971        0         0         0         0         0         0
3492887  130787974        0         0         0         0         0         0
3492888  130788053        0         0         0         0         0         0
3492889  130788054        0         0         0         0         0         0

         class_62  class_64  class_65  class_67  class_88  class_90  class_92  \
0               0         0         0         0         0         1         0
1               0         0         0         0         0         1         0
2               0         0         0         0         0         1         0
3               0         0         0         0         0         1         0
4               0         0         0         0         0         1         0
5               0         0         0         0         0         1         0
6               0         0         0         0         0         1         0
7               0         0         0         0         0         1         0
8               0         0         0         0         0         1         0
9               0         0         0         0         0         1         0
10              0         0         0         0         0         1         0
11              0         0         0         0         0         1         0
12              0         0         0         0         0         1         0
13              0         0         0         0         0         1         0
14              0         0         0         0         0         1         0
15              0         0         0         0         0         1         0
16              0         0         0         0         0         1         0
17              0         0         0         0         0         1         0
18              0         0         0         0         0         1         0
19              0         0         0         0         0         1         0
20              0         0         0         0         0         1         0
21              0         0         0         0         0         1         0
22              0         0         0         0         0         1         0
23              0         0         0         0         0         1         0
24              0         0         0         0         0         1         0
25              0         0         0         0         0         1         0
26              0         0         0         0         0         1         0
27              0         0         0         0         0         1         0
28              0         0         0         0         0         1         0
29              0         0         0         0         0         1         0
...           ...       ...       ...       ...       ...       ...       ...
3492860         0         0         0         0         0         1         0
3492861         0         0         0         0         0         1         0
3492862         0         0         0         0         0         1         0
3492863         0         0         0         0         0         1         0
3492864         0         0         0         0         0         1         0
3492865         0         0         0         0         0         1         0
3492866         0         0         0         0         0         1         0
3492867         0         0         0         0         0         1         0
3492868         0         0         0         0         0         1         0
3492869         0         0         0         0         0         1         0
3492870         0         0         0         0         0         1         0
3492871         0         0         0         0         0         1         0
3492872         0         0         0         0         0         1         0
3492873         0         0         0         0         0         1         0
3492874         0         0         0         0         0         1         0
3492875         0         0         0         0         0         1         0
3492876         0         0         0         0         0         1         0
3492877         0         0         0         0         0         1         0
3492878         0         0         0         0         0         1         0
3492879         0         0         0         0         0         1         0
3492880         0         0         0         0         0         1         0
3492881         0         0         0         0         0         1         0
3492882         0         0         0         0         0         1         0
3492883         0         0         0         0         0         1         0
3492884         0         0         0         0         0         1         0
3492885         0         0         0         0         0         1         0
3492886         0         0         0         0         0         1         0
3492887         0         0         0         0         0         1         0
3492888         0         0         0         0         0         1         0
3492889         0         0         0         0         0         1         0

         class_95  class_99
0               0         0
1               0         0
2               0         0
3               0         0
4               0         0
5               0         0
6               0         0
7               0         0
8               0         0
9               0         0
10              0         0
11              0         0
12              0         0
13              0         0
14              0         0
15              0         0
16              0         0
17              0         0
18              0         0
19              0         0
20              0         0
21              0         0
22              0         0
23              0         0
24              0         0
25              0         0
26              0         0
27              0         0
28              0         0
29              0         0
...           ...       ...
3492860         0         0
3492861         0         0
3492862         0         0
3492863         0         0
3492864         0         0
3492865         0         0
3492866         0         0
3492867         0         0
3492868         0         0
3492869         0         0
3492870         0         0
3492871         0         0
3492872         0         0
3492873         0         0
3492874         0         0
3492875         0         0
3492876         0         0
3492877         0         0
3492878         0         0
3492879         0         0
3492880         0         0
3492881         0         0
3492882         0         0
3492883         0         0
3492884         0         0
3492885         0         0
3492886         0         0
3492887         0         0
3492888         0         0
3492889         0         0

[3492890 rows x 16 columns]

In [ ]:
count=0
v = t.copy()
for index,row in v.iterrows():
    if count == 5 :
        break
    print type(row)

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,14,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,17,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,23,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,34,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,35,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
6,43,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
7,50,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
8,60,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
9,69,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,88,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
11,96,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12,106,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
13,114,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
14,115,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
15,116,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
16,130,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
17,142,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
18,147,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
19,151,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
20,168,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
21,171,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
22,173,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
23,176,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
24,184,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
25,186,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
26,195,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
27,198,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
28,204,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
29,211,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492860,130787078,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492861,130787121,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492862,130787259,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492863,130787288,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492864,130787315,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492865,130787346,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492866,130787409,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492867,130787413,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492868,130787553,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492869,130787572,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492870,130787650,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492871,130787683,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492872,130787746,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492873,130787754,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492874,130787792,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492875,130787808,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492876,130787817,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492877,130787819,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492878,130787871,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492879,130787879,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492880,130787887,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492881,130787903,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492882,130787932,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492883,130787944,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492884,130787965,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492885,130787966,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492886,130787971,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492887,130787974,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492888,130788053,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492889,130788054,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [7]:
count=0
v = t.copy()
for index,row in v.iterrows():
    if count == 5 :
        break
    count+=1
    for i,v in row.items():
        if i!= "object_id":
            print 
    print type(row)

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [14]:
type(v.loc[0])

pandas.core.series.Series

In [9]:
v.shape()

TypeError: 'tuple' object is not callable

In [10]:
type(v)

pandas.core.frame.DataFrame

In [11]:
v.shape

(3492890, 16)

In [12]:
type(v.shape)

tuple

In [13]:
v.shape[0]

3492890

In [19]:
j=v.copy()
j.replace(0,10)
print j.head()

   object_id  class_6  class_15  class_16  class_42  class_52  class_53  \
0         13        0         0         0         0         0         0
1         14        0         0         0         0         0         0
2         17        0         0         0         0         0         0
3         23        0         0         0         0         0         0
4         34        0         0         0         0         0         0

   class_62  class_64  class_65  class_67  class_88  class_90  class_92  \
0         0         0         0         0         0         1         0
1         0         0         0         0         0         1         0
2         0         0         0         0         0         1         0
3         0         0         0         0         0         1         0
4         0         0         0         0         0         1         0

   class_95  class_99
0         0         0
1         0         0
2         0         0
3         0         0
4         0         0

In [20]:
v.head()

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,14,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,17,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,23,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,34,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [21]:
t.head()

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,14,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,17,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,23,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,34,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [22]:
v.replace(0,2)

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
1,14,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
2,17,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3,23,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
4,34,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
5,35,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
6,43,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
7,50,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
8,60,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
9,69,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
10,88,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
11,96,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
12,106,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
13,114,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
14,115,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
15,116,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
16,130,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
17,142,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
18,147,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
19,151,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
20,168,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
21,171,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
22,173,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
23,176,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
24,184,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
25,186,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
26,195,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
27,198,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
28,204,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
29,211,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492860,130787078,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492861,130787121,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492862,130787259,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492863,130787288,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492864,130787315,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492865,130787346,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492866,130787409,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492867,130787413,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492868,130787553,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492869,130787572,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492870,130787650,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492871,130787683,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492872,130787746,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492873,130787754,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492874,130787792,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492875,130787808,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492876,130787817,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492877,130787819,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492878,130787871,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492879,130787879,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492880,130787887,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492881,130787903,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492882,130787932,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492883,130787944,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492884,130787965,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492885,130787966,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492886,130787971,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492887,130787974,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492888,130788053,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492889,130788054,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2

In [23]:
t.head()

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,14,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,17,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,23,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,34,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [24]:
t.replace(0,1/15)

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,14,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,17,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,23,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,34,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,35,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
6,43,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
7,50,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
8,60,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
9,69,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,88,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
11,96,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12,106,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
13,114,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
14,115,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
15,116,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
16,130,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
17,142,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
18,147,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
19,151,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
20,168,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
21,171,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
22,173,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
23,176,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
24,184,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
25,186,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
26,195,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
27,198,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
28,204,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
29,211,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492860,130787078,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492861,130787121,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492862,130787259,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492863,130787288,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492864,130787315,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492865,130787346,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492866,130787409,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492867,130787413,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492868,130787553,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492869,130787572,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492870,130787650,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492871,130787683,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492872,130787746,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492873,130787754,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492874,130787792,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492875,130787808,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492876,130787817,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492877,130787819,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492878,130787871,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492879,130787879,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492880,130787887,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492881,130787903,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492882,130787932,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492883,130787944,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492884,130787965,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492885,130787966,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492886,130787971,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492887,130787974,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492888,130788053,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492889,130788054,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [25]:
t.replace(0,2)

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
1,14,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
2,17,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3,23,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
4,34,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
5,35,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
6,43,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
7,50,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
8,60,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
9,69,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
10,88,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
11,96,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
12,106,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
13,114,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
14,115,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
15,116,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
16,130,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
17,142,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
18,147,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
19,151,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
20,168,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
21,171,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
22,173,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
23,176,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
24,184,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
25,186,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
26,195,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
27,198,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
28,204,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
29,211,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492860,130787078,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492861,130787121,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492862,130787259,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492863,130787288,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492864,130787315,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492865,130787346,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492866,130787409,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492867,130787413,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492868,130787553,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492869,130787572,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492870,130787650,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492871,130787683,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492872,130787746,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492873,130787754,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492874,130787792,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492875,130787808,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492876,130787817,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492877,130787819,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492878,130787871,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492879,130787879,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492880,130787887,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492881,130787903,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492882,130787932,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492883,130787944,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492884,130787965,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492885,130787966,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492886,130787971,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492887,130787974,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492888,130788053,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2
3492889,130788054,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2

In [26]:
t.replace(2,float(1/15))

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,14,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,17,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,23,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,34,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,35,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
6,43,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
7,50,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
8,60,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
9,69,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,88,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
11,96,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12,106,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
13,114,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
14,115,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
15,116,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
16,130,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
17,142,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
18,147,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
19,151,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
20,168,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
21,171,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
22,173,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
23,176,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
24,184,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
25,186,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
26,195,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
27,198,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
28,204,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
29,211,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492860,130787078,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492861,130787121,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492862,130787259,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492863,130787288,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492864,130787315,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492865,130787346,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492866,130787409,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492867,130787413,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492868,130787553,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492869,130787572,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492870,130787650,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492871,130787683,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492872,130787746,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492873,130787754,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492874,130787792,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492875,130787808,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492876,130787817,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492877,130787819,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492878,130787871,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492879,130787879,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492880,130787887,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492881,130787903,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492882,130787932,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492883,130787944,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492884,130787965,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492885,130787966,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492886,130787971,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492887,130787974,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492888,130788053,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3492889,130788054,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [27]:
t["class_6"].dtype

dtype('int64')

In [43]:
for i in t.head().columns:
    if i != "object_id":
        t[i] = t[i].astype(float)
print t["class_6"].dtype

float64

In [62]:
x=1.0/15.0
t=t.replace(float(0),float(x))
t=t.replace(float(1),float(x))
t

,object_id,class_6,class_15,class_16,class_42,class_52,class_53,class_62,class_64,class_65,class_67,class_88,class_90,class_92,class_95,class_99
0,13,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
1,14,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
2,17,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3,23,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
4,34,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
5,35,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
6,43,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
7,50,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
8,60,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
9,69,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
10,88,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
11,96,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
12,106,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
13,114,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
14,115,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
15,116,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
16,130,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
17,142,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
18,147,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
19,151,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
20,168,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
21,171,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
22,173,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
23,176,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
24,184,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
25,186,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
26,195,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
27,198,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
28,204,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
29,211,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492860,130787078,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492861,130787121,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492862,130787259,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492863,130787288,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492864,130787315,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492865,130787346,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492866,130787409,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492867,130787413,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492868,130787553,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492869,130787572,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492870,130787650,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492871,130787683,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492872,130787746,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492873,130787754,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492874,130787792,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492875,130787808,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492876,130787817,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492877,130787819,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492878,130787871,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492879,130787879,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492880,130787887,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492881,130787903,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492882,130787932,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492883,130787944,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492884,130787965,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492885,130787966,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492886,130787971,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492887,130787974,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492888,130788053,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
3492889,130788054,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667

In [52]:
t.loc[0,"class_6"]

0.0